language: node_js

node_js:
  - stable

install:
  - npm install

script:
  - npm run cover

services:
  - mongodb

before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"mydb_user",pwd:"abcd1234",roles:["readWrite"]});'

# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"